config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get "site/index", as: 'home'
  get "site/enconstruccion"
  post "/save_form", to:"site#save_form"
  get '/proyecto/armonia', to: 'site#armonia'
  get '/proyecto/arandanos', to: 'site#arandanos'
  get '/proyecto/riovivo', to: 'site#riovivo'
  get '/proyecto/olivar', to: 'site#olivar'
  get '/proyecto/armonia/gracias', to: 'site#gracias'
  get '/proyecto/arandanos/gracias', to: 'site#gracias'
  get '/proyecto/riovivo/gracias', to: 'site#gracias'
  get '/proyecto/olivar/gracias', to: 'site#gracias'

  get '/tyc', to: 'site#tyc'

  root "site#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nombre, :email, :cel, :proyecto)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render status: 422 }
    end
  end

  def internal_error
    respond_to do |format|
      format.html { render status: 500 }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    @proyectos = [
      {
        url: '/proyecto/armonia',
        imagen: '/sitio/proyectos/p1.png'
      },
      {
        url: '/proyecto/riovivo',
        imagen: '/sitio/proyectos/p2.png'
      },
      {
        url: '/proyecto/arandanos',
        imagen: '/sitio/proyectos/p3.png'
      },
      {
        url: '/proyecto/olivar',
        imagen: '/sitio/proyectos/p4.png'
      }
    ]
    # abort @proyectos.inspect
  end

  def enconstruccion
  end

  def save_form
    # params[:formlanding]["name"]

    if params[:formlanding]["project"] == "Olivar"
      @remitente = "bot@hablacreativo.com"
      @destinatario = "olivar@contex.com.co"
      @proyecto = "Olivar"
      @redirect_path = "/proyecto/olivar/gracias"
      @brochure = 'brochure/olivar.pdf'
    elsif params[:formlanding]["project"] == "Arándanos"
      @remitente = "bot@hablacreativo.com"
      @destinatario = "arandanos@contex.com.co"
      @proyecto = "Arándanos"
      @redirect_path = "/proyecto/arandanos/gracias"
      @brochure = 'brochure/arandanos.pdf'
    elsif params[:formlanding]["project"] == "Armonía"
      @remitente = "bot@hablacreativo.com"
      @destinatario = "lafortunaventas@verticeing.com"
      @proyecto = "Armonía"
      @redirect_path = "/proyecto/armonia/gracias"
      @brochure = 'brochure/armonia.pdf'
    elsif params[:formlanding]["project"] == "Rio Vivo"
      @remitente = "bot@hablacreativo.com"
      @destinatario = "riovivo@arconsa.com.co"
      @proyecto = "Rio Vivo"
      @redirect_path = "/proyecto/riovivo/gracias"
      @brochure = 'brochure/riovivo.pdf'
    end

    @data = {
      nombre: params[:formlanding]["name"] + " " + params[:formlanding]["lastname"],
      email: params[:formlanding]["email"],
      cel: params[:formlanding]["cel"],
      proyecto: params[:formlanding]["project"],
      destinatarios: @destinatario,
      remitente: @remitente,
      brochure: @brochure
    }

    @new_contact = Contact.new
    @new_contact.nombre = @data[:nombre]
    @new_contact.email = @data[:email]
    @new_contact.cel = @data[:cel]
    @new_contact.proyecto = @data[:proyecto]
    @new_contact.save
    
    FormMailer.nuevo_contacto(@data).deliver_now
    FormMailer.email_a_contacto(@data).deliver_now
    redirect_to @redirect_path, notice: @proyecto
  end

  def armonia
    @proyecto = "Armonía"
  end

  def arandanos
    @proyecto = "Arándanos"
  end

  def olivar
    @proyecto = "Olivar"
  end

  def riovivo
    @proyecto = "Rio Vivo"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cel %>
    <%= form.text_field :cel %>
  </div>

  <div class="field">
    <%= form.label :proyecto %>
    <%= form.text_field :proyecto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>




<script>
	var pass;
	if (localStorage.getItem("loginblog") != "logged"){
		pass = prompt("Por favor ingrese su contraseña", "");
		if(pass == "2020MillaF"){
			localStorage.setItem("loginblog", "logged");
		}else{
      window.location = "/";
		}
	}
</script>


<h1>Contactos</h1>

<table id="datatable" class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Cel</th>
      <th>Proyecto</th>
      <th>Creado</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.nombre %></td>
        <td><%= contact.email %></td>
        <td><%= contact.cel %></td>
        <td><%= contact.proyecto %></td>
        <td><%= contact.created_at.strftime("%d"+"/"+"%m"+"/"+"%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script>
    $(document).ready(function() {
        $('#datatable').DataTable({
            pageLength: '1000',
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    } );
</script>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @contact.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Cel:</strong>
  <%= @contact.cel %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= @contact.proyecto %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KXH9QV8');</script>
    <!-- End Google Tag Manager -->

    <title>Milla fontibon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/c304bff10b.js"></script>
 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.js"></script>

    <!-- <style>
        .swal2-popup{
          font-size: 14px !important;
        }
    </style> -->

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KXH9QV8"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= yield %>

   <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" ></script>

 
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">

<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>

  </body>
</html>

app/views/site/arandanos.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-center-a" style="background-color:#4aa670 !important;z-index: 999999;">
    <a class="navbar-brand" href="/">
        <img src="/armonia/Landing-Armonia-Logo-Header.png" alt="img-fluid">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" style="color:white;" href="/"><i class="fas fa-circle" style="color:#f8be51"></i> Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color:white;" href="#contactenos"><i class="fas fa-circle" style="color:#f8be51"></i> Contáctenos</a>
            </li>
        </ul>
    </div>
</nav>


<div class="barra_armonia barra_armonia_ara">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="row text-center">
                <div class="col-md-4">
                    <img src="/arandanos/Landing-Arandanos-Logo.png" class="img-fluid logo_1 logo_arandanos">
                </div>
                <div class="col-md-4">
                    <img src="/arandanos/arandanos-precio.png" class="img-fluid precio_1 precio_arandanos">
                </div>
                <div class="col-md-4">
                    <img src="/arandanos/arandanos-area.png" class="img-fluid metros_1 metros_arandanos">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="banner_principal" style="background-image:url(/arandanos/Landing-Arandanos-Banner.png) !important">
    <%= render 'site/form_proyectos', form_use: "arriba" %>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="row ">
            <div class="col-12 col-md-6 vive_arandanos">
                <img src="/arandanos/Landing-Arandanos-Foto.png" class="img-fluid">
            </div>
            <div class="col-12 col-md-6">
                <p class="p_naturaleza">Vive el momento y disfruta al máximo tu tiempo en familia</p>
                <p class="p_texto_nat">La elegancia se refleja en el proyecto Arándanos de Fontibón. Tan solo 2 torres de apartamentos regalándole a sus habitantes mucha más privacidad.</p>
                <p class="p_texto_nat">En Arándanos podrás tomarte la vida con frescura, rodeado de un ambiente natural y muy cerca de la ciudad. Serás consciente de disfrutar aquí y ahora sin preocuparte por nada más que vivir el momento y sacar el mayor provecho pasar el
                    tiempo en familia.</p>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>



<div class="disfrutaras text-center pt-5 disfrutaras_arandanos">
    <img src="/arandanos/arandanos-disfruta.png" class="img-fluid img_disfruta">
    <div class="row">
        <div class="col-8 offset-2 pt-4">
            <div class="row">
                <div class="col-6 col-md-2 offset-md-1">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_1.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_2.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_3.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_4.png" class="img-fluid">
                </div>
            </div>
            <br>
            <br>
            <div class="row">
                <div class="col-6 col-md-2 offset-md-1">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_5.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_6.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_7.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_8.png" class="img-fluid">
                </div>
                <div class="col-6 col-md-2">
                    <img src="/arandanos/Landing-Arandanos-Zona-comun_9.png" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>





<br>
<ul class="nav nav-tabs" id="myTab" role="tablist" style="width: 20%;margin: auto;">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#aptomodelo" role="tab" aria-controls="home" aria-selected="true">Apartamento Modelo</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#renders" role="tab" aria-controls="profile" aria-selected="false">Renders</a>
    </li>
</ul>
<br>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="aptomodelo" role="tabpanel" aria-labelledby="home-tab">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="/arandanos/modelo/1.jpg" class="d-block w-50 img-fluid" style="margin: 0 auto;">
              </div>
              <div class="carousel-item">
                <img src="/arandanos/modelo/2.jpg" class="d-block w-50 img-fluid" style="margin: 0 auto;">
              </div>
              <div class="carousel-item">
                <img src="/arandanos/modelo/3.jpg" class="d-block w-50 img-fluid" style="margin: 0 auto;">
              </div>
              <div class="carousel-item">
                <img src="/arandanos/modelo/4.jpg" class="d-block w-50 img-fluid" style="margin: 0 auto;">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <i class="fa fa-arrow-left i_arrow"></i>
              <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span> -->
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <i class="fa fa-arrow-right i_arrow"></i>
                <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span> -->
            </a>
          </div>
    </div>


    <div class="tab-pane fade" id="renders" role="tabpanel" aria-labelledby="profile-tab">
        <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators2" data-slide-to="0" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="/arandanos/renders/1.jpg" class="d-block w-50 img-fluid" style="margin: 0 auto;">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev">
                <i class="fa fa-arrow-left i_arrow"></i>
                <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span> -->
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next">
                <i class="fa fa-arrow-right i_arrow"></i>
                <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span> -->
            </a>
        </div>
    </div>
</div>
<br>





<p class="titulo_mapa">Un sector con proyección</p>
    <div class="container_map" id="mapa">
        <div class="center-map">
            <img src="/arandanos/Landing-arandanos-Mapa.png" class="img-fluid img-mapa hidde_el" data-enlargable width="100" style="cursor: zoom-in">
            <img src="/arandanos/Landing-arandanos-Mapa.png" class="img-fluid img-mapa show_el">
            <a href="https://goo.gl/maps/CLdvRUvY2NjQHP5i7" target="_blank"><img src="/sitio/gmaps.png" class="img-fluid waze-icon"></a>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        
        <script>
            $('img[data-enlargable]').addClass('img-enlargable').click(function(){
                var src = $(this).attr('src');
                $('<div>').css({
                    background: 'RGBA(0,0,0,.5) url('+src+') no-repeat center',
                    backgroundSize: 'contain',
                    width:'100%', height:'100%',
                    position:'fixed',
                    zIndex:'10000',
                    top:'0', left:'0',
                    cursor: 'zoom-out'
                }).click(function(){
                    $(this).remove();
                }).appendTo('body');
            });
        </script>
    </div>
    <br> <br>

<div class="p-5" id="contactenos">
    <%= render 'site/form_proyectos', form_use: "abajo" %>
</div>


<div class="row text-center div_cta">
    <div class="col-12 col-md-12">
        <p class="text_cta">Conoce más sobre tu proyecto soñado dando clic<br> para descargar nuestro brochure</p>
        <a href="/brochure/arandanos.pdf" target="_blank" class="btn btn_cta">Descargar</a>
    </div>
</div>


<div class="row text-center bg-footer-in">
    <div class="col-8 offset-2">
        <div class="row">
            <div class="col-12 col-md-12 text-center">
                <img src="/sitio/titulo_footer_general.png" class="img-fluid" style="width: 40%;margin-bottom: 14px;">
            </div>
            <div class="col-12 col-md-12 text-center">
                <img src="/enconstruccion/Logo estamos en construccion_1.png" class="img-fluid">
            </div>
        </div>
    </div>
</div>

app/views/site/enconstruccion.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Milla Fontibón</title>
    <style>
        html, body{
            overflow: hidden !important;
            white-space: nowrap;
            height: 100%;
        }
        .bg-ec{
            background-image: url('/enconstruccion/Fondo estamos en construccion.png');
            background-size: cover;
        }
        .bg-footer-ec{
            background-color: #123a5c;
            padding: 20px 0px;
            position: absolute;
            width: 104%;
            bottom: 0;
        }
        .ht-ec{
            height: 100vh !important;
            align-items: center;
            margin-top: -50px;
        }
        
    </style>
  </head>
  <body class="bg-ec">

    <div class="row ht-ec">
        <div class="col-8 offset-2">
            <div class="row">
                <div class="col-12 col-md-6 text-md-left text-center">
                    <img src="/enconstruccion/Logo estamos en construccion_3.png" class="img-fluid img-center-ec">
                </div>
                <div class="col-12 col-md-6 text-md-right text-center mt-5">
                    <img src="/enconstruccion/Copy estamos en construccion.png" class="img-fluid img-center-ec">
                </div>
            </div>
        </div>
    </div>


    <div class="row text-center bg-footer-ec">
        <div class="col-8 offset-2">
            <div class="row">
                <div class="col-4">
                    <img src="/enconstruccion/Logo estamos en construccion.png" class="img-fluid">
                </div>
                <div class="col-4">
                    <img src="/enconstruccion/Logo estamos en construccion_1.png" class="img-fluid">
                </div>
                <div class="col-4">
                    <img src="/enconstruccion/Logo estamos en construccion_2.png" class="img-fluid">
                </div>
            </div>
        </div>
    </div>




    
  </body>
</html>